format_version: v1.0
type: UniqueComponent
attributes: {id: hemc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: CS_4_END_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0x61ffffff'}
  - type: KeyValueSet
    attributes: {id: CS_4_MEMORY_BANK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '12'}
  - type: Hex
    attributes: {id: CS_4_MEMORY_BASE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
      - type: User
        attributes: {value: '4096'}
  - type: KeyValueSet
    attributes: {id: CS_4_MEMORY_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: CS_4_RAM_CHECK_BIT_INIT_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '33554432'}
  - type: Comment
    attributes: {id: HEMC_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** HEMC is running at 100000000 Hz ****'}
  - type: KeyValueSet
    attributes: {id: HSDRAMC_CR__NB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '1'}
  - type: KeyValueSet
    attributes: {id: HSDRAMC_CR__NC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '1'}
  - type: KeyValueSet
    attributes: {id: HSDRAMC_CR__NR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: Menu
    attributes: {id: HSDRAMC_FEATURE_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: HSDRAMC_MR_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: HSDRAMC_TIMING_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: HSDRAMC_TR_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '195'}
  - type: Comment
    attributes: {id: HSDRAM_COMPONENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: HSMC_CHIP_SELECT4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: Hex
    attributes: {id: SDRAMC_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1677721600'}
  - type: Boolean
    attributes: {id: USE_HSDRAM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
  - type: Boolean
    attributes: {id: USE_HSMC_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
  - type: Boolean
    attributes: {id: USE_HSMC_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
  - type: Boolean
    attributes: {id: USE_HSMC_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
  - type: Boolean
    attributes: {id: USE_HSMC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
  - type: Boolean
    attributes: {id: USE_HSMC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'false'}
  - type: Boolean
    attributes: {id: USE_HSMC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'true'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: hemc}
